# Generated by Django 2.2.13 on 2020-08-07 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsstask',
            name='frequency',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='频率(分钟)'),
        ),
        migrations.AlterField(
            model_name='rsstask',
            name='url',
            field=models.CharField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='RSS地址'),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='频率(分钟)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='headers',
            field=models.TextField(blank=True, help_text='自定义请求头，如可以设置cookie获取登录后才能查看的页面', verbose_name='自定义请求头'),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='监控网址'),
        ),
    ]
