# Generated by Django 2.2.13 on 2020-08-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200807_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='regular_expression',
            field=models.CharField(blank=True, help_text='使用正则表达式进一步提取信息，可以留空', max_length=500, verbose_name='正则表达式'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rule',
            field=models.CharField(blank=True, help_text='规则写法参考文档，留空则只简单监控内容变化', max_length=500, verbose_name='监控规则'),
        ),
        migrations.AlterField(
            model_name='task',
            name='selector',
            field=models.CharField(max_length=500, verbose_name='元素选择器'),
        ),
    ]
