# Generated by Django 2.2.13 on 2021-01-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200814_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='selector',
            field=models.TextField(verbose_name='元素选择器'),
        ),
    ]
