# Generated by Django 2.2.13 on 2021-01-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210131_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.TextField(blank=True, verbose_name='消息体模板'),
        ),
    ]
