# Generated by Django 2.2.13 on 2021-03-14 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210203_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsstask',
            name='url',
            field=models.CharField(max_length=1000, validators=[django.core.validators.URLValidator()], verbose_name='RSS地址'),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(max_length=1000, validators=[django.core.validators.URLValidator()], verbose_name='监控网址'),
        ),
    ]
