# Generated by Django 2.2.13 on 2021-01-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '日志查看',
                'verbose_name_plural': '日志查看',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=512, verbose_name='邮箱地址 / Server 酱 SCKEY / Pushover User Key / Bark key / 自定义网址'),
        ),
    ]
