# Generated by Django 2.2.13 on 2021-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20210131_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackBotSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Slack OAuth Access Token')),
            ],
            options={
                'verbose_name': 'Slack Bot 设置',
                'verbose_name_plural': 'Slack Bot 设置',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=512, verbose_name='邮箱地址 / Server 酱 SCKEY /             Pushover User Key / Bark key / 自定义网址 / Slack channel'),
        ),
    ]
