# Generated by Django 2.2.13 on 2021-02-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20210201_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlackBotSetting',
            new_name='SlackSetting',
        ),
        migrations.AlterModelOptions(
            name='slacksetting',
            options={'verbose_name': 'Slack 设置', 'verbose_name_plural': 'Slack 设置'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, '邮箱'), (1, '微信'), (2, 'pushover'), (3, 'Bark'), (4, '自定义通知'), (5, 'Slack')], default='邮箱', verbose_name='通知方式类型'),
        ),
    ]
